### ISSUE TITLE
请问和合本CUV有吗？

### ISSUE THREAD

**Issue by jdleung** [liudongmiao/bibledata#1]
链接中有这一版本，但似乎没有提供下载的链接
https://www.biblegateway.com/versions/Chinese-Union-Version-Simplified-CUVS/#booklist

谢谢

**Comment by liudongmiao** [comment]
这个版本非常古老，不适合现在使用。

一般来说，建议使用后续两个版本：
1. 中国大陆使用的 和合本
2. 和合本新标点版（又分为两个版本，新标点和合本 与 现代标点和合本）
新标点和合本：https://github.com/dove-bible/cu89s
现代标点和合本：https://www.biblegateway.com/versions/Chinese-Union-Version-Modern-Punctuation-Simplified-CUVMPS/#booklist

**Comment by jdleung** [comment]
就是想结合和合本修订版和这个旧版对比一下。

biblegateway的下载整本圣经是需要登录吗？还是只有网页版？
