### ISSUE TITLE
bibledata-af-afr53.zip contribution

### ISSUE THREAD

**Issue by digir0n** [liudongmiao/bibledata#6]
Good day .

I am compiling af53 version that I like to contribute.
In the "chapters" table inside the "content" fields I found the following issue.

```
Gen <span class="v0_
Exod <span class="v1_
Lev <span class="v2_
and then
Num <span class="v4_
```

I would have expected this 
    Num <span class="v3_

Is this an issue that you are going to change, or must I just compile my version the same?
I started like this 
   Gen <span class="v1_
    Exod <span class="v2_
    Lev <span class="v3_
    Num <span class="v4_

But then bookmarks for first three chapters don't work properly.

Thank you.
ronald.de.villiers@gmail.com

**Comment by liudongmiao** [comment]
Please check original link, it should be on the list from bibles.org or biblegateway.

**Comment by liudongmiao** [comment]
for bibledata, see 13a43c65f55830f3d1c1fcc673e3fe8eb24c85d1
