### ISSUE TITLE
bibledata-af-afr53 spelling/grammar

### ISSUE THREAD

**Issue by digir0n** [liudongmiao/bibledata#7]
Thank you for afr53 version.

There is some spelling and grammar issues. I have a complete afr53 version of all the verses in the exact format you use. 
Can I mail it to you?
I am also finished compiling the OT chapters and busy with NT chapters.

**Comment by liudongmiao** [comment]
Sorry for the late response. Please email me.

**Comment by liudongmiao** [comment]
duplicate in #6
