### ISSUE TITLE
ESV chapters database only has chapter titles

### ISSUE THREAD

**Issue by pixelsage** [liudongmiao/bibledata#9]
Just a few versions for comparison:

**ESV**, **KJV**: Some `chapters` content fields have only the `<h3>` chapter title, while others have that plus the actual chapter text. `verses` unformatted field has only text.
**NASB**, **NKJV**: `chapters` has the chapter title plus content. `verses` sometimes contain chapters in the text.

As a side note, it is sort of weird that `chapters` are formatted, but `verses` are not.

**Comment by liudongmiao** [comment]
please give me the screenshot, thanks.
